export const INPUT_VALUE = 'INPUT_VALUE'

export const FIND_POST_SUMMARY_LIST = "FIND_POST_SUMMARY_LIST";
export const FIND_POST_SUMMARY_LIST_SUCCESS = "FIND_POST_SUMMARY_LIST_SUCCESS";
export const FIND_POST_SUMMARY_LIST_FAIL = "FIND_POST_SUMMARY_LIST_FAIL";

export const FIND_POST_DETAIL_ONE = "FIND_POST_DETAIL_ONE";
export const FIND_POST_DETAIL_ONE_SUCCESS = "FIND_POST_DETAIL_ONE_SUCCESS";
export const FIND_POST_DETAIL_ONE_FAIL = "FIND_POST_DETAIL_ONE_FAIL";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_FAIL = "UPDATE_POST_FAIL";

export const REMOVE_POST = "REMOVE_POST";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const REMOVE_POST_FAIL = "REMOVE_POST_FAIL";
