server:
  port: 9999

security:
  oauth2:
    client:
      clientId: myClient
      clientSecret: myClientSecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
    resource.jwt:
      key-pair:
        alias: reservationkey
        store-password: reservationpass

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    generate-ddl: false
#    show-sql: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: testuser
#    password: password
#    driver-class-name: org.postgresql.Driver
